### ISSUE TITLE
Firebase Error

### ISSUE THREAD

**Issue by arjun-k-r** [pradyotprksh/NewNeighbourlyAppkication#1]
Hi, I have downloaded your code and updated google-services.json file with my firebase settings.
App is crashing:-
2018-12-27 15:46:36.133 7695-7695/com.prakash.pradyot.newapplication E/ViewRootImpl: sendUserActionEvent() returned.
2018-12-27 15:46:38.099 7695-7695/com.prakash.pradyot.newapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.prakash.pradyot.newapplication, PID: 7695
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.google.firebase.firestore.QuerySnapshot.getDocumentChanges()' on a null object reference
        at com.prakash.pradyot.newapplication.Home.HomeActivity$6.onEvent(HomeActivity.java:193)
        at com.prakash.pradyot.newapplication.Home.HomeActivity$6.onEvent(HomeActivity.java:190)
        at com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2(com.google.firebase:firebase-firestore@@17.1.4:894)
        at com.google.firebase.firestore.Query$$Lambda$3.onEvent(Unknown Source:6)
        at com.google.firebase.firestore.util.ExecutorEventListener.lambda$onEvent$0(com.google.firebase:firebase-firestore@@17.1.4:42)
        at com.google.firebase.firestore.util.ExecutorEventListener$$Lambda$1.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
2018-12-27 15:46:38.179 3266-3285/? E/PhoneWindow_APM :: isCalledPackage return false
2018-12-27 15:46:38.806 5418-5592/? E/PBSessionCacheImpl: sessionId[23830161185459878] not persisted.
2018-12-27 15:46:48.230 3266-4651/? E/Watchdog: !@Sync 15038 [2018-12-27 15:46:48.230]

Kindly help me to resolve this.

**Comment by pradyotprksh** [comment]
Have you enable Firestore into your firebase project. i think because of that its showing that error.

**Comment by pradyotprksh** [comment]
> Hi, I have downloaded your code and updated google-services.json file with my firebase settings.
> App is crashing:-
> 2018-12-27 15:46:36.133 7695-7695/com.prakash.pradyot.newapplication E/ViewRootImpl: sendUserActionEvent() returned.
> 2018-12-27 15:46:38.099 7695-7695/com.prakash.pradyot.newapplication E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.prakash.pradyot.newapplication, PID: 7695
> java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.google.firebase.firestore.QuerySnapshot.getDocumentChanges()' on a null object reference
> at com.prakash.pradyot.newapplication.Home.HomeActivity$6.onEvent(HomeActivity.java:193)
> at com.prakash.pradyot.newapplication.Home.HomeActivity$6.onEvent(HomeActivity.java:190)
> at com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2(com.google.firebase:firebase-firestore@@17.1.4:894)
> at com.google.firebase.firestore.Query$$Lambda$3.onEvent(Unknown Source:6)
> at com.google.firebase.firestore.util.ExecutorEventListener.lambda$onEvent$0(com.google.firebase:firebase-firestore@@17.1.4:42)
> at com.google.firebase.firestore.util.ExecutorEventListener$$Lambda$1.run(Unknown Source:6)
> at android.os.Handler.handleCallback(Handler.java:789)
> at android.os.Handler.dispatchMessage(Handler.java:98)
> at android.os.Looper.loop(Looper.java:164)
> at android.app.ActivityThread.main(ActivityThread.java:6944)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
> 2018-12-27 15:46:38.179 3266-3285/? E/PhoneWindow_APM :: isCalledPackage return false
> 2018-12-27 15:46:38.806 5418-5592/? E/PBSessionCacheImpl: sessionId[23830161185459878] not persisted.
> 2018-12-27 15:46:48.230 3266-4651/? E/Watchdog: !@sync 15038 [2018-12-27 15:46:48.230]
> 
> Kindly help me to resolve this.

Have you enable Firestore into your firebase project? i think because of that its showing that error.

**Comment by arjun-k-r** [comment]
Hi , Awesome , working fine now :) .
Kindly mail me your contact number at arjun.kumar21@gmail.com.
Need to discuss with you.

Thanks buddy.
